### ISSUE TITLE
when I try to run this I keep getting this error could someone help me please 

### ISSUE THREAD

**Issue by ZaidenTheGreat** [SadanandJaiswal/leetcode-clone#1]
<img width="1470" alt="Screenshot 2024-09-06 at 1 28 55 PM" src="https://github.com/user-attachments/assets/face808c-96ef-4e71-9c7f-65c982817d79">

**Comment by SadanandJaiswal** [comment]
> <img alt="Screenshot 2024-09-06 at 1 28 55 PM" width="1470" src="https://private-user-images.githubusercontent.com/144372829/365256183-face808c-96ef-4e71-9c7f-65c982817d79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2ODc2NTYsIm5iZiI6MTcyNTY4NzM1NiwicGF0aCI6Ii8xNDQzNzI4MjkvMzY1MjU2MTgzLWZhY2U4MDhjLTk2ZWYtNGU3MS05YzdmLTY1Yzk4MjgxN2Q3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwN1QwNTM1NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYmZiZGI2YTRjY2NjNDJmYTJjMTAyZDA3YTJhMGM2MjNkY2QyYzU1ZjNhNjEzMTM1MjE2MWY2M2YyZmYxZmZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.76Hxp0y7eqRA_8hVnjWAhbYEPawwBqP0eduCRZEE14Y">

When you are getting this error?

**Comment by SadanandJaiswal** [comment]
It seems like you are encountering this error because the .env file might
not have been used, or the necessary API keys for Firebase are missing or
incorrectly configured.

To resolve this, please check the following:

   1. Ensure that you have created a .env file in your project root and
   included the Firebase API keys in it.
   2. Make sure that the API key and other Firebase configuration variables
   (like authDomain, projectId, etc.) are correctly set in the .env file.
   3. If you're using environment variables, double-check that they are
   correctly referenced in your code.

If the issue persists after these checks, feel free to share more details,
and I’ll be happy to assist further.

**Comment by ZaidenTheGreat** [comment]
where do you get the firebase api key
